CampusSelectionWebApplication/CampusSelectionWebApplication/Controllers/CandidateController.cs
using CampusSelectionCustomExceptions;
using CampusSelectionWebApplication.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CampusSelectionWebApplication.Controllers
{
    public class CandidateController : Controller
    {
        private readonly IManagerModel _managerModel;

        public CandidateController(IManagerModel managerModel)
        {
            _managerModel = managerModel;
        }

        public ActionResult AddCandidate()
        {
            return View();
        }

       
        [HttpPost]

        public async Task<IActionResult> AddCandidate(CandidateModel candidateModel)
        {
            try
            {
                if (await _managerModel.AddCandidate(candidateModel))
                {
                    ViewBag.Message = "Added Successfully";
                }
                else
                {
                    ViewBag.Message = "Couldnt Add";
                }
            }
            catch (SQlException ex)
            {
                ViewBag.Message = ex.Message;
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetCandidateDetails()
        {
            List<CandidateModel> candidateModel = await _managerModel.GetCandidateDetails();
            return View(candidateModel);
        }

       
    }
}

CampusSelectionWebApplication/CampusSelectionWebApplication/Views/Candidate/AddCandidate.cshtml
@model CampusSelectionWebApplication.Models.CandidateModel

@{
    ViewData["Title"] = "AddCandidate";
}

<h1>AddCandidate</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form id="form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                    <label asp-for="CandidateId" class="control-label"></label>
                    <input asp-for="CandidateId" class="form-control" />
                    <span asp-validation-for="CandidateId" class="text-danger"></span>
                </div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TechniccalSpecification" class="control-label"></label>
                <input asp-for="TechniccalSpecification" class="form-control" />
                <span asp-validation-for="TechniccalSpecification" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsSelected" class="control-label"></label>
                <input asp-for="IsSelected" class="form-control" />
                <span asp-validation-for="IsSelected" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CollegeId" class="control-label"></label>
                <input asp-for="CollegeId" class="form-control" />
                <span asp-validation-for="CollegeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="button" id="btnClick" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    @Html.ActionLink("Get List of Students" , "GetCandidateDetails","Candidate")
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

        <script>
        $(document).ready(function () {
            $('#btnClick').click(function () {
                var data = $('#form').serialize();
                $.ajax({
                    type: 'POST',
                    url: '/Candidate/AddCandidate',
                    data: data,
                    success: function (data) {
                        alert("Candidate added successfully");
                    },
                    error: function (err) {
                        alert("Something went wrong! Please try again");
                    }
                })
            })
            $('#Name').mouseover(function () {
                $('#Name').css('background-color', 'aqua');
            })
            $('#Name').mouseout(function () {
                $('#Name').css('background-color', 'white');
            })
            $('#TechniccalSpecification').mouseover(function () {
                $('#TechniccalSpecification').css('background-color', 'aqua');
            })
            $('#TechnicalSpecification').mouseout(function () {
                $('#TechnicalSpecification').css('background-color', 'white');
            })
            $('#IsSelected').mouseover(function () {
                $('#IsSelected').css('background-color', 'aqua');
            })
            $('#IsSelected').mouseout(function () {
                $('#IsSelected').css('background-color', 'white');
            })
            $('#CollegeId').mouseover(function () {
                $('#CollegeId').css('background-color', 'aqua');
            })
            $('#CollegeId').mouseout(function () {
                $('#CollegeId').css('background-color', 'white');
            })
        })
        </script>
    
}

CampusSelectionWebApplication/CampusSelectionWebApplication/Views/Candidate/GetCandidateDetails.cshtml
@model IEnumerable<CampusSelectionWebApplication.Models.CandidateModel>

@{
    ViewData["Title"] = "GetCandidateDetails";
}

<h1>GetCandidateDetails</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CandidateId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TechniccalSpecification)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsSelected)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CollegeId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CandidateId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TechniccalSpecification)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsSelected)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CollegeId)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>